In [2]:
import pandas
from tqdm.notebook import tqdm
import numpy as np
from ast import literal_eval

In [3]:
df_paths_related = pandas.read_csv('related_paths.csv', header=None)

df_paths_related = df_paths_related.replace(np.nan, '', regex=True)

df_paths_related

0  1
0                                                   []  1
1    ['my', 'love', 'my', 'life', 'google', 'my', '...  1
2    ['amazon', 'prime', 'samsung', 'prime', 'samsu...  1
3    ['member', 'login', 'family', 'member', 'membe...  1
4                                                   []  1
..                                                 ... ..
295                                                 []  0
296                                                 []  0
297                                                 []  0
298                                                 []  0
299                                                 []  0

[300 rows x 2 columns]

In [4]:
df_domains_related = pandas.read_csv('related_domains.csv', header=None).replace(np.nan, '', regex=True)

df_domains_related

0     1
0    ['am', 'pm', 'am', 'pm', 'to', 'modi', 'pm', '...     1
1    ['lagu', 'lirik', 'download', 'lagu', 'ku', 'k...     1
2                                                   []  ['']
3    ['chrysler', 'lhs', 'chrysler', 'lhs', 'school...     1
4    ['tiny', 'house', 'tiny', 'houses', 'tiny', 'h...     1
..                                                 ...   ...
295  ['no', 'deposit', 'bank', 'deposit', 'direct',...     0
296  ['no', 'deposit', 'bank', 'deposit', 'direct',...     0
297  ['no', 'deposit', 'bank', 'deposit', 'direct',...     0
298  ['no', 'deposit', 'bank', 'deposit', 'direct',...     0
299  ['no', 'deposit', 'bank', 'deposit', 'direct',...     0

[300 rows x 2 columns]

In [5]:
df_paths = pandas.read_csv('paths.csv', header=None).replace(np.nan, '', regex=True)

df_paths

0  1
0                                                   []  1
1    ['sign', 'pie', 'wp', 'success', 'includes', '...  1
2                                  ['prime', 'mobile']  1
3    ['pw', 'bootstrap', 'register', 'php', 'css', ...  1
4                                                   []  1
..                                                 ... ..
295                                               ['']  0
296                                               ['']  0
297                                               ['']  0
298                                               ['']  0
299                                               ['']  0

[300 rows x 2 columns]

In [6]:
df_domains = pandas.read_csv('domains.csv', header=None).replace(np.nan, '', regex=True)


df_domains

0  1
0           ['pm', 'pay', 'back']  1
1    ['ku', 'ch', 'khas', 'bate']  1
2                            ['']  1
3                   ['lhs', 'lt']  1
4                        ['tiny']  1
..                            ... ..
295         ['deposit', 'photos']  0
296         ['deposit', 'photos']  0
297         ['deposit', 'photos']  0
298         ['deposit', 'photos']  0
299         ['deposit', 'photos']  0

[300 rows x 2 columns]

In [7]:
(size, _) = df_domains.shape

domains = []
labels_domains = []

paths = []
labels_paths = []


for i in tqdm(range(size)):
    
    domain = literal_eval(df_domains.iloc[i].tolist()[0])
    label_domain = df_domains.iloc[i].tolist()[1]
    
    path = literal_eval(df_paths.iloc[i].tolist()[0])
    label_path = df_paths.iloc[i].tolist()[1]
    
    domains.append(domain)
    labels_domains.append(label_domain)
    
    paths.append(path)
    labels_paths.append(label_path)

In [8]:
domains

[['pm', 'pay', 'back'],
 ['ku', 'ch', 'khas', 'bate'],
 [''],
 ['lhs', 'lt'],
 ['tiny'],
 ['mbc', 'lm'],
 ['in', 'for', 'ef', 'mb'],
 ['in', 'for', 'ef', 'mb'],
 ['solicit', 'ar', 'multi', 'plus'],
 ['appa', 'thy', 'safe', 'br'],
 [''],
 ['appa', 'thy', 'safe', 'br'],
 ['ref', 'sec', 'mb'],
 ['ref', 'sec', 'mb'],
 ['sec', 'smb'],
 ['sec', 'smb'],
 ['section', 'pf', 'mb'],
 ['section', 'pf', 'mb'],
 ['arc', 're', 'pro', 'web', 'host', 'app'],
 ['is', 'sbk', 'muf', 'in', 'kinj'],
 ['secure', 'secure', 'web', 'session'],
 ['client', 'co', 'mumbler'],
 ['x', 'sph'],
 ['x', 'sph'],
 ['appa', 'thy', 'safe', 'br'],
 ['tesla'],
 ['ds', 'gn', 'pool'],
 ['of', 'us', 'even', 'ment', 'draco', 'niro'],
 ['client', 'co', 'mumbler'],
 ['my', 'billing', 'login'],
 ['audio', 'booked'],
 ['sad'],
 ['ud', 'inca', 'ko', 'web', 'host', 'app'],
 ['ud', 'inca', 'ko', 'web', 'host', 'app'],
 ['www', 'zona', 'segura', 'sbn'],
 ['cbb'],
 ['aude', 'of', 'web'],
 ['duct', 'port', 'ails', 'fire', 'base', 'app'],
 

In [9]:
len(paths)

300

In [10]:
(size, _) = df_domains_related.shape

domains_related_queries = []
labels_domains_related = []

for i in tqdm(range(size)):
    
    domain = literal_eval(df_domains_related.iloc[i].tolist()[0])
    label_domain = df_domains_related.iloc[i].tolist()[1]
    
    domains_related_queries.append(domain)
    labels_domains_related.append(label_domain)

In [11]:
len(domains_related_queries)

300

In [12]:
(size, _) = df_paths_related.shape

paths_related_queries = []
labels_paths_related_queries = []

for i in tqdm(range(size)):
    
    path = literal_eval(df_paths_related.iloc[i].tolist()[0])
    label_path = df_paths_related.iloc[i].tolist()[1]
    
    paths_related_queries.append(path)
    labels_paths_related_queries.append(label_path)

In [13]:
paths_related_queries

[[],
 ['my',
  'love',
  'my',
  'life',
  'google',
  'my',
  'my',
  'account',
  'my',
  'name',
  'my',
  'facebook',
  'my',
  'friend',
  'my',
  'ip',
  'my',
  'girl',
  'my',
  'location',
  'my',
  'way',
  'my',
  'little',
  'pony',
  'my',
  'mp3',
  'my',
  'pay',
  'make',
  'my',
  'trip',
  'book',
  'my',
  'show',
  'my',
  'music',
  'my',
  'school',
  'my',
  'email',
  'my',
  'family',
  'my',
  'address',
  'my',
  'red',
  'my',
  'mail',
  'what',
  'is',
  'my',
  'ip',
  'rate',
  'my',
  'professor'],
 ['amazon',
  'prime',
  'samsung',
  'prime',
  'samsung',
  'video',
  'prime',
  'galaxy',
  'prime',
  'j7',
  'j7',
  'prime',
  'amazon',
  'video',
  'prime',
  'amazon',
  'video',
  'grand',
  'prime',
  'prime',
  'minister',
  'samsung',
  'galaxy',
  'prime',
  'samsung',
  'galaxy',
  'samsung',
  'grand',
  'prime',
  'samsung',
  'j7',
  'prime',
  'samsung',
  'j7',
  'j5',
  'j5',
  'prime',
  'galaxy',
  'grand',
  'prime',
  'j2',
  'prime'

In [14]:
def jaccard_similarity(list1, list2):
    
    s1 = set(list1)
    s2 = set(list2)
    
    if len(s1.union(s2)) != 0:
        return len(s1.intersection(s2)) / len(s1.union(s2))
    
    else:
        return 0

In [15]:
#Jaccard index between domains and related queries

size_domains_related_queries = len(domains_related_queries)

j_indexes_domain_related = []

labels_j_indexes_domain_related = labels_domains_related

for i in tqdm(range(size_domains_related_queries)):
    
    domain_related = domains_related_queries[i]
    
    registered_domain = domains[i]
    
    j_indexes_domain_related.append(jaccard_similarity(registered_domain, domain_related))

In [16]:
# Jaccard index between paths and related queries

size_paths_related_queries = len(paths_related_queries)

j_indexes_paths_related = []

labels_j_indexes_path_related = labels_paths_related_queries

for i in tqdm(range(size_paths_related_queries)):
    
    path = paths[i]
    
    path_related = paths_related_queries[i]
    
    j_indexes_paths_related.append(jaccard_similarity(path_related, path))

In [17]:
j_indexes_paths_related_to_domain = [] #Jaccard index related queries domain and paths

j_indexes_domain_related_to_paths = [] #Jaccard index related queries path and domain

j_indexes_domain_path = [] #Jaccard index between paths and domains

j_indexes_related_to_path_related_to_domain = []

size = len(paths_related_queries)

for i in tqdm(range(size)):
    
    j_indexes_paths_related_to_domain.append(jaccard_similarity(paths[i],domains_related_queries[i]))
    
    j_indexes_domain_related_to_paths.append(jaccard_similarity(paths_related_queries[i],domains[i]))
    
    j_indexes_domain_path.append(jaccard_similarity(paths[i],domains[i]))
    
    j_indexes_related_to_path_related_to_domain.append(jaccard_similarity(paths_related_queries[i],domains_related_queries[i]))

In [38]:
from sklearn.preprocessing import label_binarize

j_indexes = []

j_indexes.extend(j_indexes_paths_related_to_domain)
j_indexes.extend(j_indexes_domain_related_to_paths)
j_indexes.extend(j_indexes_domain_path)
j_indexes.extend(j_indexes_related_to_path_related_to_domain)
j_indexes.extend(j_indexes_paths_related)
j_indexes.extend(j_indexes_domain_related)

labels = []

labels.extend(labels_paths)
labels.extend(labels_paths)
labels.extend(labels_paths)
labels.extend(labels_paths)
labels.extend(labels_paths)
labels.extend(labels_paths)

#              ,
#              j_indexes_domain_path,
#              j_indexes_related_to_path_related_to_domain,
#              j_indexes_paths_related,
#              j_indexes_domain_related,)

# j_indexes = [j_indexes_paths_related_to_domain,
#              j_indexes_domain_related_to_paths,
#              j_indexes_domain_path,
#              j_indexes_related_to_path_related_to_domain,
#              j_indexes_paths_related,
#              j_indexes_domain_related,
#             ]
# df_j_indexes = pandas.DataFrame(j_indexes)
# df_j_indexes

In [42]:
from sklearn.model_selection import train_test_split

random_state = 42

train_features, test_features, train_labels, test_labels = train_test_split(
    j_indexes,
    labels,
    test_size = 0.25,
    random_state = random_state
)

In [46]:
import numpy as np
from sklearn. ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, roc_auc_score

#Training model with random forest

n_estimators = 1000

rf = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')

rf.fit(np.array(train_features).reshape(-1,1), np.array(train_labels).reshape(-1,1))

#Testing model and finding error

predictions = rf.predict(np.array(test_features).reshape(-1,1))

probs = rf.predict_proba(np.array(test_features).reshape(-1,1))[:, 1]

matrix = confusion_matrix(np.array(test_labels).reshape(-1,1), predictions)

roc_value = roc_auc_score(np.array(test_labels).reshape(-1,1), probs)

print(matrix)
print(roc_value)

[[202  29]
 [161  58]]
0.6024135681669928


/home/groot/.local/lib/python3.6/site-packages/ipykernel_launcher.py:13: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  del sys.path[0]


In [53]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

clf = SVC(gamma='auto')

#Training Model

clf.fit(np.array(train_features).reshape(-1,1), np.array(train_labels).reshape(-1,1))

#Testing model and finding error

predictions = clf.predict(np.array(test_features).reshape(-1,1))

matrix = confusion_matrix(np.array(test_labels).reshape(-1,1), predictions)

print(matrix)

[[  0 231]
 [  0 219]]


/home/groot/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [50]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(np.array(train_features).reshape(-1,1), np.array(train_labels).reshape(-1,1))

#Predict Output
predictions= model.predict(np.array(test_features).reshape(-1,1)) # 0:Overcast, 2:Mild

probs = model.predict_proba(np.array(test_features).reshape(-1,1))[:, 1]

matrix = confusion_matrix(np.array(test_labels).reshape(-1,1), predictions)

roc_value = roc_auc_score(np.array(test_labels).reshape(-1,1), probs)

print(matrix)
print(roc_value)

[[ 39 192]
 [ 40 179]]
0.5282175967107474


/home/groot/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
